from bson import ObjectId
from typing import List, Optional
from pydantic import BaseModel, Field

# Create Potential Questions Schema
class PotentialQuestionCreate(BaseModel):
    doc_id: str = Field(..., description="ID of the associated document")
    chunk_index: int = Field(..., description="Index of the chunk in the document")
    potential_questions: List[str] = Field(..., description="Potential questions of the chunk generated by LLM")
    embedding_ids: List[str] = Field(..., description="Embedding IDs of potential questions that stored in ChromaDB")
    
    class Config:
        from_attributes = True
        extra = "forbid"
        
# Update A Potential Question Schema
class PotentialQuestionUpdate(BaseModel):
    new_question: str = Field(..., description="New question content for update")
    
    class Config:
        from_attributes = True
        extra = "forbid"
        
# Add A Potential Question Schema
class AddPotentialQuestion(BaseModel):
    question: str = Field(..., description="The potential question to be added")
    
    class Config:
        from_attributes = True
        extra = "forbid"
        
# Potential Questions Response Schema
class PotentialQuestionResponse(BaseModel):
    doc_id: str = Field(...)
    chunk_index: int = Field(...)
    potential_questions: List[str] = Field(...)
    embedding_ids: List[str] = Field(...)
    created_at: str = Field(...)
    updated_at: Optional[str] = None
    
    class Config:
        from_attributes = True
        populate_by_name = True
        json_encoders = { ObjectId: str }